const LOGOS = {
    gmail: require("./gmail.png"),
    linkedIn: require("./linkedin.png"),
    nextJs: require("./next-js.png"),
    nextJsHQ: require("./next-js-HQ.png"),
    phone: require("./phone.png"),
    twitter: require("./x.png"),
    javaScript: require("./javascript.png"),
    javaScriptHQ: require("./javascript-HQ.png"),
    typeScript: require("./typescript.png"),
    typeScriptHQ: require("./typescript-HQ.png"),
    mongoDB: require("./mongo-db.png"),
    mongoDBHQ: require("./mongo-db-HQ.png"),
    react: require("./react.png"),
    reactHQ: require("./react-HQ.png"),
    tailwind: require("./tailwind-css.png"),
    tailwindHQ: require("./tailwind-css-HQ.png"),
    axios: require("./axios.png"),
    axiosHQ: require("./axios-HQ.png"),
    createReactApp: require("./create-react-app.png"),
    createReactAppHQ: require("./create-react-app-HQ.png"),
    css: require("./css.png"),
    cssHQ: require("./css-HQ.png"),
    html: require("./html.png"),
    htmlHQ: require("./html-HQ.png"),
    expressJs: require("./express-js.png"),
    expressJsHQ: require("./express-js-HQ.png"),
    nodeJs: require("./node-js.png"),
    nodeJsHQ: require("./node-js-HQ.png"),
    redux: require("./redux.png"),
    reduxHQ: require("./redux-HQ.png"),
    sass: require("./sass.png"),
    sassHQ: require("./sass-HQ.png"),
    styledComponents: require("./styled-components.png"),
    styledComponentsHQ: require("./styled-components-HQ.png"),
    vite: require("./vite.png"),
    viteHQ: require("./vite-HQ.png"),
    figma: require("./figma.png"),
    figmaHQ: require("./figma-HQ.png"),
};

//Fast-to-import modules
export default LOGOS;
